blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"
urlpatterns = [
    path('', views.all_posts, name="blog_list"),
]

bloggers_corner/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls')),
    path('blog/', include('blog.urls')),
    path('contactus/', include('contactus.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
]

contactus/urls.py
from django.urls import path
from contactus import views

app_name = "contactus"
urlpatterns = [
    path('', views.contactus, name="contactus")
]

gallery/urls.py
from django.urls import path
from gallery import views

app_name = "gallery"
urlpatterns = [
    path('', views.gallery_list, name="gallery_list"),
    path('<int:id>', views.gallery_detail, name="gallery_detail"),
]

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    category = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

contactus/models.py
from djongo import models

# Create your models here.
class Contactus(models.Model):
    name = models.CharField(max_length=60)
    email = models.EmailField()
    message = models.TextField()

gallery/models.py
from djongo import models

# Create your models here.
class Gallery(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.CharField(max_length=100)

class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    item = models.ForeignKey('Gallery', on_delete=models.CASCADE)

users/models.py
from django.db import models

# Create your models here.

contactus/forms.py
from django import forms

class ContactusForm(forms.Form):
    name = forms.CharField(max_length=60)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

gallery/forms.py
from django import forms
from django.forms.fields import CharField


class CommentForm(forms.Form):
    # author = CharField(
    #     max_length=60,
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Your Name"
    #         }
    #     )
    # )
    body = CharField(
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Leave a  comment!"
            }
        )
    )

blog/views.py
from django.shortcuts import render
from blog.models import Blog

# Create your views here.
def all_posts(request):
    blogs_objects = Blog.objects.all()

    return render(request, 'blog/index.html', { 'blogs_objects': blogs_objects })

contactus/views.py
from django.http.request import HttpRequest
from django.shortcuts import render
from django.http import HttpResponse
from contactus.forms import ContactusForm
from contactus.models import Contactus

# Create your views here.
def contactus(request: HttpRequest):
    myForm = ContactusForm()

    if request.method == 'POST':
        myForm = ContactusForm(request.POST)
        if myForm.is_valid():
            name = myForm.cleaned_data['name']
            email = myForm.cleaned_data['email']
            message = myForm.cleaned_data['message']

            contactus = Contactus(name = name, email = email, message = message)
            contactus.save()

            notify = "Hi {}, we received your message".format(name)

            return HttpResponse(notify)

    return render(request, 'contactus/contactus.html', { 'myForm': myForm })

gallery/views.py
from django.http.request import HttpRequest
from django.shortcuts import render
from gallery.models import Gallery, Comment
from gallery.forms import CommentForm
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.
def gallery_list(request):
    gallery_objects = Gallery.objects.all()

    return render(request, 'gallery/gallery.html', { 'gallery_objects': gallery_objects })

@login_required
def gallery_detail(request: HttpRequest, id):
    gallery_item = Gallery.objects.get(id = id)
    form = CommentForm()

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            # author = form.cleaned_data['author']
            author = request.user.username
            body = form.cleaned_data['body']

            comment = Comment(author = author, body = body, item = gallery_item)
            comment.save()
    
    comments = Comment.objects.filter(item=id)

    return render(request, 'gallery/detail.html', { 'gallery_item': gallery_item, 'comments': comments, 'form': form })

users/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-8 offset-md-2">
  <h1>Blog Posts</h1>
  {% for post in blogs_objects %}
  <hr />
  <h2>{{ post.title }}</h2>
  <small>
    {{ post.created_on }} |&nbsp; category: {{ post.category }}&nbsp;
  </small>
  <p>{{ post.body }}</p>
  {% endfor %}
</div>
{% endblock %}

bloggers_corner/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blogger's Corner</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:blog_list' %}">Blogger's Corner</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'gallery:gallery_list' %}">Gallery</a>
            </li>

            <li class="nav-item">  
              <a class="nav-link" href="{% url 'contactus:contactus' %}">Contact us</a>
            </li>  
            
            {% if user.is_authenticated %}
            <li class="nav-item">  
              <a class="nav-link" href="{% url 'password_change' %}">Change Password</a>
            </li> 

            <li class="nav-item">  
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li> 
            {% else %}
            <li class="nav-item">  
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li> 
            {% endif %}
          </ul>
        </div>
    </div>
</nav>

<div class="container">
  <h3>Hello, {{user.username|default:'Guest'}} <h3/> 
    
  {% block content %}{% endblock %}  
</div>

</body>
</html>

contactus/templates/contactus/contactus.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ myForm.as_p }}
    <input type="submit" name="btn btn-primary" value="Submit" />
</form>
{% endblock %}

gallery/templates/gallery/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>{{ gallery_item.title }}</h1>
<div class="row">
    <div class="col-md-6">
        <img src="{% static gallery_item.image %}" alt="{{ gallery_item.title }}" width="100%">
        <h5>About the image</h5>
        <p>{{ gallery_item.description }}</p>
    </div>
    
    <div class="col-md-6">
        {% if user.is_authenticated %}
        <h3>Leave a comment</h3>
        <form method="POST">
            {% csrf_token %}
            <!-- <div class="form-group">
                {{ form.author }}
            </div> -->
            <div class="form-group">
                {{ form.body }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

        <hr />
        {% endif %}

        <h3>Comments</h3>
        {% for comment in comments %}
        <p>
            On {{ comment.created_on }}&nbsp;
            <b>{{ comment.author }}</b> wrote:
        </p>
        <p>{{ comment.body }}</p>

        <hr />
        {% endfor %}
    </div>
</div>
{% endblock %}

gallery/templates/gallery/gallery.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<h1>Gallery</h1>
	<div class="row">
		{% for item in gallery_objects %}
			<div class="col-md-4">
				<div class="card mb-2">
					<img class="card-img-top" src="{% static item.image %}" alt="{{ item.title }}" />
					<div class="card-body">
						<h5 class="card-title">{{ item.title }}</h5>
						<p class="card-text">{{ item.description }}</p>
						<a href="{% url 'gallery:gallery_detail' item.id %}" class="btn btn-primary">Read More</a>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}